model:
  name: "facebook/wav2vec2-large-960h"

sampling_rate:
  target: 16000

api:
  infer_url: "http://localhost:8001/asr"
  ping_url: "http://localhost:8001/ping"

paths:
  data_dir: "../common_voice"
  output_dir: "."
  csv_name: "cv-valid-dev.csv"